apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    harvesterhci.io/vmRunStrategy: RerunOnFailure
    network.harvesterhci.io/ips: '[]'
  labels:
    harvesterhci.io/creator: harvester
    harvesterhci.io/os: ubuntu
  name: iot
  namespace: iot-vm
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '["s05891-ssh-keys/s05891-public-key"]'
      labels:
        harvesterhci.io/vmName: iot
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - name: disk-0
              disk:
                bus: virtio
              bootOrder: 1
            - name: cloudinitdisk
              disk:
                bus: virtio
          inputs:
          - bus: usb
            name: tablet
            type: tablet
          interfaces:
          - bridge: {}
            model: virtio
            name: default
        features:
          acpi:
            enabled: true
        machine:
          type: q35
        memory:
          guest: 924Mi
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
      evictionStrategy: LiveMigrate
      hostname: iot
      networks:
      - multus:
          networkName: harvester-networks/vlan70
        name: default
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: iot-disk-0-urbcc
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: iot-eeqee
            networkDataSecretRef:
              name: iot-eeqee
