apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  namespace: iot-vm
  annotations:
    harvesterhci.io/volumeClaimTemplates: >-
      [{"metadata":{"name":"iot-disk-0-tb9ov","annotations":{"harvesterhci.io/imageId":"s05891-images/image-qxdmp"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"20Gi"}},"volumeMode":"Block","storageClassName":"longhorn-image-qxdmp"}}]
    network.harvesterhci.io/ips: '[]'
  labels:
    harvesterhci.io/creator: harvester
  name: iot
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '["s05891-ssh-keys/s05891-public-key"]'
      labels:
        harvesterhci.io/vmName: iot
    spec:
      domain:
        machine:
          type: ''
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - bridge: {}
              model: virtio
              name: default
          disks:
            - name: disk-0
              disk:
                bus: virtio
              bootOrder: 1
            - name: cloudinitdisk
              disk:
                bus: virtio
        resources:
          limits:
            memory: 2Gi
            cpu: 2
        features:
          acpi:
            enabled: true
      evictionStrategy: LiveMigrate
      hostname: iot
      networks:
        - name: default
          multus:
            networkName: harvester-networks/vlan70
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: iot-disk-0-tb9ov
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: s05891-cloud-config/db
      accessCredentials: []
